# Generated by Django 4.0.3 on 2022-04-02 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0004_alter_habit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='date_complete',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='habit',
            name='start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('habit', 'date_created'), name='one_record_per_day'),
        ),
    ]
