# Generated by Django 4.0.3 on 2022-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0004_alter_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='one_record_per_day'),
        ),
    ]
