# Generated by Django 4.0.3 on 2022-03-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0005_habit_date_tracker_one_record_per_day'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tracker',
            name='one_record_per_day',
        ),
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('habit', 'date_complete'), name='one_record_per_day'),
        ),
    ]
