# Generated by Django 4.0.3 on 2022-03-27 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0006_remove_tracker_one_record_per_day_alter_habit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
