# Generated by Django 4.0.3 on 2022-03-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0007_alter_habit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='date',
        ),
    ]
