# Generated by Django 4.0.3 on 2022-03-28 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0008_remove_habit_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tracker',
            name='one_record_per_day',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='date_complete',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='habit',
            name='start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('habit', 'date_created'), name='one_record_per_day'),
        ),
    ]
